sudo: required
dist: trust
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
          packages:
          - gcc-4.9
          - g++-4.9
          - lcov
      env: CXX_COMPILER=g++ C_COMPILER=gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libopencv-dev
    #    - pip install --user cpp-coveralls
install:
#- pip install -r requirements.txt
#- pip install coveralls
# install GTest and GMock
- sudo apt-get -qq install libgtest-dev
- "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
- sudo apt-get -qq install google-mock
- "cd /usr/src/gmock && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
# install latest LCOV (1.9 was failing)
# TODO - what version do we get from apt-get?
- cd ${TRAVIS_BUILD_DIR}
  #- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  #- tar xf lcov_1.11.orig.tar.gz
  #- sudo make -C lcov-1.11/ install
- sudo apt-get -qq install lcov
- gem install coveralls-lcov
- lcov --version
- g++ --version

before_cache:
- cd ${TRAVIS_BUILD_DIR}
- mkdir build

cache:
  directories:
  - build/ext/iproute2
  - protobuf

before_script:
  - sudo ./install-protobuf.sh
script:
- cd build
- cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && cmake --build .
- ctest -V
        #          - ./configure --enable-gcov && make && make check
after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture -o coverage.info
- lcov -r coverage.info '*_test.cc' '*\.pb\.*' '*/iproute2/*' '/usr/include/*' '*/gtest/*' -o coverage.info
- lcov --list coverage.info
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
